name = "partigle"
version = "0.1.0"
description = "AtomVM experiments with Gleam"

licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.40"
gleam_erlang = "~> 0.26"

[dev-dependencies]
#gleeunit = "~> 0.10"
